IF NOT EXISTS (
	SELECT * FROM sys.databases 
	WHERE name = 'SMSDb'
) 
BEGIN
	CREATE DATABASE SMSDb
END

USE SMSDb
GO


IF NOT EXISTS (
	SELECT * FROM sys.objects 
	WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[PRODUCTS]') AND TYPE IN (N'U')
)
BEGIN
	CREATE TABLE [dbo].[PRODUCTS](
	[ProductID] [VARCHAR] (20) NOT NULL ,
	[ProductName] [NVARCHAR] (200) NOT NULL,
	[Price] [DECIMAL] (18,2) DEFAULT 0,	
	CONSTRAINT PK_ProductID PRIMARY KEY(ProductID)
	)
END

IF NOT EXISTS (
	SELECT * FROM sys.objects 
	WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[CUSTOMERS]') AND TYPE IN (N'U')
)
BEGIN 
	CREATE TABLE [dbo].[CUSTOMERS] (
		[CustomerID] [VARCHAR] (20) NOT NULL ,
		[CustomerName] [NVARCHAR] (255) NOT NULL,
		[Phone] [VARCHAR] (10) NOT NULL,
		CONSTRAINT PK_CustomerID PRIMARY KEY (CustomerID)
	)
END

IF NOT EXISTS (
	SELECT * FROM sys.objects 
	WHERE OBJECT_ID = OBJECT_ID(N'INVOICES') AND TYPE IN (N'U')
)
BEGIN 
	CREATE TABLE [dbo].[INVOICES](
	[InvoiceID] [VARCHAR] (20) NOT NULL,
	[CustomerID] [VARCHAR] (20) NOT NULL,
	[InvoiceDate] Date NOT NULL,
	[TotalPrice] [DECIMAL] (18,2) NOT NULL DEFAULT 0,
	CONSTRAINT PK_InvoiceID PRIMARY KEY (InvoiceID),
	CONSTRAINT FK_CUSTOMERS_CustomerID_INVOICES_InvoiceID FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID)
	)
END


IF NOT EXISTS (
	SELECT * FROM sys.objects 
	WHERE OBJECT_ID = OBJECT_ID(N'INVOICEDETAILS') AND TYPE IN (N'U')
)
BEGIN
	CREATE TABLE [dbo].[INVOICEDETAILS] (
		[InvoiceDetailID] [VARCHAR] (20) NOT NULL,
		[InvoiceID] [VARCHAR] (20) NOT NULL,
		[ProductID] [VARCHAR] (20) NOT NULL,
		[Quatity] [INT] NOT NULL DEFAULT 0,
		[TotalPrice] [DECIMAL] (18,2) NOT NULL DEFAULT 0,

		CONSTRAINT PK_InvoiceDetailID PRIMARY KEY (InvoiceDetailID),
		CONSTRAINT FK_InvoiceID FOREIGN KEY (InvoiceID) REFERENCES INVOICES(InvoiceID),
		CONSTRAINT FK_ProductID FOREIGN KEY (ProductID) REFERENCES PRODUCTS(ProductID)
	)
END
